### ISSUE TITLE
NGC 6548, 6549, 6550

### ISSUE THREAD

**Issue by pchev** [mattiaverga/OpenNGC#28]
This was reported for CdC here: https://www.ap-i.net/mantis/view.php?id=2474

NED has the same identification than OpenNGC, but Hyperleda and Simbad differ.
6548 must be the bigger galaxy, actually identified as 6550.
6549 is the smaller edge on. 
6550 is an error, indicated as duplicate of 6548 in Hyperleda and Simbad.

http://leda.univ-lyon1.fr/ledacat.cgi?o=ngc6548
http://leda.univ-lyon1.fr/ledacat.cgi?o=ngc6549
http://leda.univ-lyon1.fr/ledacat.cgi?o=ngc6550

See other link in the CdC report.

**Comment by mattiaverga** [comment]
This is another case where NED, Simbad and Hyperleda don't agree... yep, the general consensus here seems that NED is wrong and the other two agree and I'm inclined to diverge OpenNGC from NED (which I generally maintain as source of truth).
I just want to try to contact someone at NED to ask why they differ from the other sources and to see if they're willing to uniform NED to the general consensus.

**Comment by mattiaverga** [comment]
So, NED reply was super fast. They're going to reconsider the identification and from what I understand they're taking great care of the work of [Harold Corwin](http://haroldcorwin.net/ngcic/index.html).
Since Corwin's work is licensed under CC-BY-SA-3.0 it should be compatible with OpenNGC (CC-BY-SA-4.0), so I would like to make a full review of OpenNGC database upon Corwin's database and check some controversial identifications which I decided on my own judgment in the past...

In the meantime. this is fixed in 34eb86b

**Comment by pchev** [comment]
Thank you Mattia, I will update CdC as soon I return home this week.

**Comment by mattiaverga** [comment]
I've also started to review discrepancies between OpenNGC and Corwin's catalog, it will take some time. I'll push a new release after the review is finished.
